### ISSUE TITLE
Grading Overview

### ISSUE THREAD

**Issue by lucav17** [tina-pina/bwa-u4-feature-request#1]
### Criteria 1: Objective Section  
* _Score Level:_ 4
* _Comment(s):_ I like that you added two features and that both were feasible to achieve!
 
### Criteria 2: Background Section
* _Score Level:_ 4
* _Comment(s):_ I like how you centered your logic around the UX. I think the UX of a website is extremely important and the fact that your features add into the experience is great.
 
### Criteria 3: Technical Design Section
* _Score Level:_ 4
* _Comment(s):_ I think you handled both well. One thing I would ask, is why not use onChange instead of onKeyUp?
 
### Criteria 4: Caveats Section
* _Score Level:_ 4
* _Comment(s):_ One thing you can do is instead of fetching the url everytime to preview a song, you could find a pattern and generate the URL or asynchronously fetch all URL's in the background and make it available to the user.
 
### Overall Score: 16/16
Great job!

**Comment by tina-pina** [comment]
Thank you for your preview! :)
